"""

Revision ID: 2c31b9c5457d
Revises: 6f38ece99613
Create Date: 2025-09-09 18:13:47.381455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c31b9c5457d'
down_revision = '6f38ece99613'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'daily_limit')
    op.drop_column('users', 'monthly_limit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('monthly_limit', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('daily_limit', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
