"""

Revision ID: 9cf63acccb79
Revises: 7360b4ce9574
Create Date: 2025-08-04 14:07:42.012980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cf63acccb79'
down_revision = '7360b4ce9574'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('establishments', sa.Column('owner_telegram_id', sa.BigInteger(), nullable=True))
    op.drop_constraint('fk_establishments_owner_user_id_users', 'establishments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_establishments_owner_telegram_id_users'), 'establishments', 'users', ['owner_telegram_id'], ['telegram_id'])
    op.drop_column('establishments', 'owner_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('establishments', sa.Column('owner_user_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_establishments_owner_telegram_id_users'), 'establishments', type_='foreignkey')
    op.create_foreign_key('fk_establishments_owner_user_id_users', 'establishments', 'users', ['owner_user_id'], ['id'])
    op.drop_column('establishments', 'owner_telegram_id')
    # ### end Alembic commands ###
