"""

Revision ID: 6f38ece99613
Revises: 977c2bf71462
Create Date: 2025-09-09 17:44:59.241499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f38ece99613'
down_revision = '977c2bf71462'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('establishments', sa.Column('owner_id', sa.BigInteger(), nullable=True))
    op.drop_constraint('fk_establishments_owner_telegram_id_users', 'establishments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_establishments_owner_id_users'), 'establishments', 'users', ['owner_id'], ['id'])
    op.drop_column('establishments', 'owner_telegram_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('establishments', sa.Column('owner_telegram_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_establishments_owner_id_users'), 'establishments', type_='foreignkey')
    op.create_foreign_key('fk_establishments_owner_telegram_id_users', 'establishments', 'users', ['owner_telegram_id'], ['telegram_id'])
    op.drop_column('establishments', 'owner_id')
    # ### end Alembic commands ###
